### ISSUE TITLE
Loading Nemoh results and conversion

### ISSUE THREAD

**Issue by martijnwilpshaar** [izabala123/BEMRosetta#3] opened 2020-04-23 13:57 UTC
Hi there, 

Many thanks for sharing your application first of all, it looks neat!

Now going over to my issue: 
I am interested in conversion of my Nemoh results into .Wamit such that I can upload this data into different softwares related to wind turbine design (like Bladed, OpenFAST etc.). Your tool should be capable of doing this, correct? 

However, when I try to go over to the hydrodynamic coefficients section and load my .tec files it gives as warning "Unknown BEM file extension". Also attached the warning. 

Am I missing something?

Many thanks in advance!

![image](https://user-images.githubusercontent.com/52451695/80107094-f7e97d00-857a-11ea-8957-c485487903e5.png)

**Comment by izabala123** [comment] 2020-04-29 10:01
Hello Martijnwilpshaar

Thank you very much.

The solution of the issue is easy: For now, in case of Nemoh files, nemoh.cal file has to be opened.

In any case, you have given me the idea of supporting also to open the nemoh.cal file from the .tec file in results folder.

Best regards
Iñaki

**Comment by izabala123** [comment] 2020-04-29 13:15
Hello Martijnwilpshaar

New version allows to load .tec files in a results folder under a nemoh.cal file.

Best regards
Iñaki

**Comment by martijnwilpshaar** [comment] 2020-04-29 13:28
Dear Iñaki,

Many thanks for your replies! Following your approach, I now used BemRosetta is used to output .1 (hydrodynamic coefficients), .3 (excitation force) and .hst (hydrostatic stiffness).
This already helps a lot, but I’m not there yet. Bladed is also asking (besides the .1, .3 and .hst files) for a .cfg, .frc and .out file, see attachment. I’m now trying to find the structure of these files and see if I can manually make these files.
Maybe this can also be a great addition for your tool in the upcoming versions.

Kind regards,
Martijn

**Comment by izabala123** [comment] 2020-04-29 15:48
Dear Martijn

I am happy that the problem is solved. Please do not forget to indicate
that in Github for me to close the issue.
I am sorry but I cannot see any enclosed file in your email.

I do not know .cfg and .frc files, but if you could send me samples I could
try to get them. .out is not a simple format, but I know it and I could try
to get it.

Best regards
Iñaki

**Comment by martijnwilpshaar** [comment] 2020-04-30 06:52
Dear Iñaki,

Yes, you helped me a lot! These are the files the program Bladed is asking for. The .cfg file is only needed for the IALTFRC value so that would be easy. Also, the .frc is easy to make by putting the mass/inertia matrix in correct format. The .out file is a bit more tricky. 

![image](https://user-images.githubusercontent.com/52451695/80680310-cdd61480-8abe-11ea-8d03-a1d6d4614a1a.png)

Kind regards, 

Martijn

**Comment by izabala123** [comment] 2020-04-30 08:58
I have created this new issue with your last post: 
[](https://github.com/izabala123/BEMRosetta/issues/4)

**Closed** 2020-04-30 08:58 UTC
Labels: enhancement
